# site title
title: Just another developer log

# user name or organization name
user: jie

# issue repository
repository: issue_blog

# multi-author
authors: Yang

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 7#2d87fd77345ddc3c73e036b9926260b2471a6a9

# posts per page
perpage: 20


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
